### ISSUE TITLE
Causes rebooting

### ISSUE THREAD

**Issue by Ant1q** [roleoroleo/yi-hack-Allwinner.gdrive#3]
After installing every motion event casuses reboot, but still uploading files to GDrive
Log of Autoremover
```
-----STARTING GDriveAutoremover Mon Dec  7 17:39:26 EET 2020
sh: 15476981760: out of range
-----STARTING GDriveAutoremover Mon Dec  7 17:41:04 EET 2020
sh: 15476981760: out of range
-----STARTING GDriveAutoremover Mon Dec  7 17:42:43 EET 2020
sh: 15476981760: out of range
```
uploader

```
-----STARTING GDriveUploader at Mon Dec  7 17:39:09 EET 2020
new generated files count 21 2020Y12M07D17H
-----STARTING GDriveUploader at Mon Dec  7 17:40:28 EET 2020
-----STARTING GDriveUploader at Mon Dec  7 17:42:43 EET 2020
```

debug
```
Checking remote directory access: be21.a0AfH6SMATtT1IAYjeQVqC3exWbX8h-ka4dlroSHbaFSdnNYfDtmANcYzRMr1HL24zp4466SBKt_fS-zDfuR7BqPU6YmXMxYT1yorJZy-8HOtjj3e_f87SoAxr6zxw4cIvuT2NOytYyNFKkxidaskgspLxTPgulC0Y5lCYZjDfNBW7_M 1Vclvi6LZQI2M0-8WnWGy6QaZi7EN8E1M 2020Y12M07D17H 10ol6NSnwxCdIOiro3RqQgTWIb0fdqxdD
directory: 2020Y12M07D17H, {'name': '15M28S32.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '16M00S60.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '17M00S60.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '18M00S60.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '19M00S60.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '37M00S59.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '39M26S34.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '41M05S55.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '42M45S15.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '43M00S59.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
directory: 2020Y12M07D17H, {'name': '44M00S60.mp4', parents: ['16pKKr8BoWObr8bgF3bwGcp4dj2qC67NY']}
```
It happens on firmwares 0.2.0 - 0.2.2
Any advice?

**Comment by roleoroleo** [comment]
Is it the same problem?
https://github.com/roleoroleo/yi-hack-MStar.gdrive/issues/8

**Comment by Ant1q** [comment]
Hm... SUDDENLY =) There are two different problems. Cheap SDCard makes reboots, after change to SanDisk it stops, but still have "out of range" and AutoRemover is not working, Google Drive is full and i have `WARNING: Sat Dec 12 20:44:03 EET 2020 : Can not send the file /tmp/sd/record/2020Y12M12D20H/42M00S60.mp4. May be it is too big. File was skipped`
same to MStar problem

**Comment by roleoroleo** [comment]
For "out of range", try the last commit I pushed.

**Comment by Ant1q** [comment]
after update
uploader log
```
WARNING: Mon Dec 14 20:09:34 EET 2020 : Can not send the file /tmp/sd/record/2020Y12M14D20H/08M00S60.mp4. Something happen. Trying to send the file again
{ "error": { "errors": [ { "domain": "global", "reason": "storageQuotaExceeded", "message": "The user's Drive storage quota has been exceeded." } ], "code": 403, "message": "The user's Drive storage quota has been exceeded." } } 
```

remover

```
WARNING: Mon Dec 14 14:24:03 EET 2020 : Can not get quota info. Something happen. Trying to get quota info again
WARNING: Mon Dec 14 14:24:09 EET 2020 : Can not get quota info. Something happen. Trying to get quota info again
WARNING: Mon Dec 14 14:24:16 EET 2020 : Can not get quota info. Token was expired. Trying to refresh token and get quota info again
sh: 15584317441: out of range
sh: 15743940808: out of range
sh: 15872501100: out of range
sh: 16004947630: out of range
sh: 16100177995: out of range
sh: 16106081569: out of range
sh: 16106081569: out of range
```

GDrive is full, last uploaded file - in 16th hour

and for example remover log from camera without last commit (i have 2 cameras)
```
WARNING: Mon Dec 14 14:28:22 EET 2020 : Can not get quota info. Something happen. Trying to get quota info again
/tmp/sd/yi-hack/gdrive/GDriveAutoremover: line 259: stat: not found
sh: 524288: unknown operand
WARNING: Mon Dec 14 14:28:29 EET 2020 : Can not get quota info. Token was expired. Trying to refresh token and get quota info again
/tmp/sd/yi-hack/gdrive/GDriveAutoremover: line 259: stat: not found
sh: 524288: unknown operand
sh: 16097714722: out of range
sh: 16097714722: out of range
sh: 16097714722: out of range
sh: 16097714722: out of range
sh: 16097714722: out of range
sh: 16105932265: out of range
sh: 16105932265: out of range
sh: 16105932265: out of range
```

**Comment by Ant1q** [comment]
Hello again. I still have a problem with autoremover. It does not delete files from GDrive.
I added log-lines in .sh:
```
read_conf_files >> ${log}
get_folder_list >> ${log}
remove_folder >> ${log}
get_space_info >> ${log}
start_autoremover >> ${log} 2>&1 &
exit 0
```

and now logfile shows this

```
-----STARTING GDriveAutoremover Sun Jan  3 14:17:28 EET 2021
WARNING: Sun Jan  3 14:17:29 EET 2021 : Can not get folders. Something happen. Trying to get folders. again
WARNING: Sun Jan  3 14:17:35 EET 2021 : Can not get folders. Something happen. Trying to get folders. again
WARNING: Sun Jan  3 14:17:41 EET 2021 : Can not get folders. Something happen. Trying to get folders. again
WARNING: Sun Jan  3 14:17:47 EET 2021 : Can not get folders. Something happen. Trying to get folders. again
```

**Comment by sebzgt2k** [comment]
Hi do you have some news about this issue ?

**Comment by Ant1q** [comment]
Nope, I gave up and wrote a little bash script that runs rclone on my home automation server and cleans up the google drive
